# IMPORTANT: Thesis-specific reliability analysis for quantitative renal MRI.
#
# Run this script from the ``Analysis/BRAINSFit_Registration`` folder after
# ``Analysis.py`` has created the four private BRAINSFit input CSV tables.
# The script analyses healthy volunteers and CKD patients independently and
# writes CoV, ICC, and Bland--Altman outputs only within this folder.
#
# The CoV implementation follows the published de Boer et al. formulation,
# adapted here for the final renal MRI data structure. This script requires the
# R packages tidyverse and irr. Do not commit input tables or generated outputs
# containing study data to a public repository.

library(tidyverse)
library(irr)

# ------------------------------------------------------------
# T1/T2 kidney MRI statistics
# Separate analyses for healthy volunteers and CKD patients:
# CoV + ICC + Bland-Altman
# ------------------------------------------------------------
# Inputs are generated by the Python processing pipeline.
# Each row is one whole-kidney ROI measurement.

script_path <- tryCatch(
  normalizePath(sys.frame(1)$ofile, winslash = "/", mustWork = TRUE),
  error = function(e) NA_character_
)

analysis_dir <- if (!is.na(script_path)) dirname(script_path) else getwd()

# ------------------------------------------------------------
# Read input
# ------------------------------------------------------------

read_input <- function(path) {
  read_csv(path, show_col_types = FALSE) %>%
    mutate(
      ID = as.character(ID),
      site = as.character(site),
      vendor = as.character(vendor),
      visit = as.character(visit),
      anatomy = as.character(anatomy),
      parameter = as.character(parameter),
      value = as.numeric(value)
    ) %>%
    filter(anatomy == "whole")
}

run_group_analysis <- function(
    group_name,
    group_label,
    repeatability_file,
    reproducibility_file
) {
  group_output_dir <- file.path(analysis_dir, group_name)
  dir.create(group_output_dir, recursive = TRUE, showWarnings = FALSE)

  repeatability_data <- read_input(repeatability_file)
  reproducibility_data <- read_input(reproducibility_file)

# ------------------------------------------------------------
# Pair measurements
# ------------------------------------------------------------

make_visit_pairs <- function(dataset, visit1, visit2) {
  
  dataset %>%
    filter(visit %in% c(visit1, visit2)) %>%
    select(ID, site, vendor, visit, parameter, value) %>%
    pivot_wider(
      names_from = visit,
      values_from = value
    ) %>%
    filter(
      !is.na(.data[[visit1]]),
      !is.na(.data[[visit2]])
    ) %>%
    transmute(
      ID,
      site,
      vendor,
      parameter,
      v1 = .data[[visit1]],
      v2 = .data[[visit2]],
      diff = v1 - v2,
      ave = (v1 + v2) / 2,
      ratio = diff^2 / ave^2
    )
  
}

# ------------------------------------------------------------
# CoV
# ------------------------------------------------------------

calculate_cov <- function(df, grouping_vars) {
  
  df %>%
    na.omit() %>%
    group_by(across(all_of(grouping_vars))) %>%
    summarise(
      N = n(),
      CV = 100 * sqrt(1 / (2 * N) * sum(ratio)),
      .groups = "drop"
    ) %>%
    filter(N >= 3)
  
}

cov_site <- function(df) {
  calculate_cov(df, c("parameter", "site"))
}

cov_vendor <- function(df) {
  calculate_cov(df, c("parameter", "vendor"))
}

cov_total <- function(df) {
  calculate_cov(df, "parameter") %>%
    mutate(group = "Total")
}

run_cov <- function(dataset, visit1, visit2) {
  
  pairs <- make_visit_pairs(dataset, visit1, visit2)
  
  list(
    pairs = pairs,
    site = cov_site(pairs),
    vendor = cov_vendor(pairs),
    total = cov_total(pairs)
  )
  
}

# ------------------------------------------------------------
# Analyses
# ------------------------------------------------------------

analyses <- list(
  
  repeatability = list(
    data = repeatability_data,
    visit1 = "v2a",
    visit2 = "v3"
  ),
  
  reproducibility = list(
    data = reproducibility_data,
    visit1 = "v2a",
    visit2 = "v3"
  )
  
)

cov_results <- purrr::imap(
  analyses,
  ~ run_cov(.x$data, .x$visit1, .x$visit2)
)

# ------------------------------------------------------------
# Merge outputs
# ------------------------------------------------------------

repeatability_cov <- bind_rows(
  
  cov_results$repeatability$site %>%
    rename(Group = site) %>%
    mutate(Analysis = "Center"),
  
  cov_results$repeatability$vendor %>%
    rename(Group = vendor) %>%
    mutate(Analysis = "Vendor"),
  
  cov_results$repeatability$total %>%
    rename(Group = group) %>%
    mutate(Analysis = "Total")
  
) %>%
  select(
    Analysis,
    parameter,
    Group,
    N,
    CV
  )

reproducibility_cov <- bind_rows(
  
  cov_results$reproducibility$site %>%
    rename(Group = site) %>%
    mutate(Analysis = "Center"),
  
  cov_results$reproducibility$vendor %>%
    rename(Group = vendor) %>%
    mutate(Analysis = "Vendor"),
  
  cov_results$reproducibility$total %>%
    rename(Group = group) %>%
    mutate(Analysis = "Total")
  
) %>%
  select(
    Analysis,
    parameter,
    Group,
    N,
    CV
  )

# ------------------------------------------------------------
# Save results
# ------------------------------------------------------------

write_csv(
  repeatability_cov,
  file.path(group_output_dir, "Repeatability_CoV.csv")
)

write_csv(
  reproducibility_cov,
  file.path(group_output_dir, "Reproducibility_CoV.csv")
)

# ------------------------------------------------------------
# Print results
# ------------------------------------------------------------

cat("\n==============================\n")
cat(group_label, "\n")
cat("==============================\n")
cat("Repeatability CoV\n")
cat("==============================\n")
print(repeatability_cov)

cat("\n==============================\n")
cat("Reproducibility CoV\n")
cat("==============================\n")
print(reproducibility_cov)

cat("\nCoV tables successfully saved.\n")
# ------------------------------------------------------------
# ICC analysis
# ------------------------------------------------------------
# Preserve original DWI methodology:
# ICC(2,1), two-way random effects, absolute agreement, single measurement.

calculate_icc_one_group <- function(df) {
  df_ICC <- df %>%
    select(v1, v2) %>%
    na.omit()
  
  if (nrow(df_ICC) < 3) {
    return(tibble(
      N_pairs = nrow(df_ICC),
      ICC = NA_real_,
      Lower_CI = NA_real_,
      Upper_CI = NA_real_,
      F_value = NA_real_,
      P_value = NA_real_
    ))
  }
  
  icc_res <- tryCatch(
    icc(
      df_ICC[, c("v1", "v2")],
      model = "twoway",
      type = "agreement",
      unit = "single"
    ),
    error = function(e) NULL
  )
  
  if (is.null(icc_res)) {
    return(tibble(
      N_pairs = nrow(df_ICC),
      ICC = NA_real_,
      Lower_CI = NA_real_,
      Upper_CI = NA_real_,
      F_value = NA_real_,
      P_value = NA_real_
    ))
  }
  
  tibble(
    N_pairs = nrow(df_ICC),
    ICC = icc_res$value,
    Lower_CI = icc_res$lbound,
    Upper_CI = icc_res$ubound,
    F_value = icc_res$Fvalue,
    P_value = icc_res$p.value
  )
}

calculate_icc_grouped <- function(pairs, grouping_vars, grouping_label, group_column = NULL) {
  pairs %>%
    group_by(across(all_of(grouping_vars))) %>%
    group_modify(~ calculate_icc_one_group(.x)) %>%
    ungroup() %>%
    filter(N_pairs >= 3) %>%
    mutate(
      Level = grouping_label,
      Group = if (is.null(group_column)) "Total" else as.character(.data[[group_column]]),
      Parameter = parameter
    ) %>%
    select(
      Level,
      Group,
      Parameter,
      N_pairs,
      ICC,
      Lower_CI,
      Upper_CI,
      F_value,
      P_value
    )
}

run_icc <- function(dataset, visit1, visit2, analysis_label) {
  pairs <- make_visit_pairs(dataset, visit1, visit2)
  
  bind_rows(
    calculate_icc_grouped(
      pairs,
      c("parameter", "site"),
      grouping_label = "Center",
      group_column = "site"
    ),
    calculate_icc_grouped(
      pairs,
      c("parameter", "vendor"),
      grouping_label = "Vendor",
      group_column = "vendor"
    ),
    calculate_icc_grouped(
      pairs,
      c("parameter"),
      grouping_label = "Overall"
    )
  ) %>%
    mutate(Analysis = analysis_label, .before = Level)
}

ICC_results <- purrr::imap_dfr(
  analyses,
  ~ run_icc(
    dataset = .x$data,
    visit1 = .x$visit1,
    visit2 = .x$visit2,
    analysis_label = str_to_title(.y)
  )
)

print("ICC results")
print(ICC_results)

write_csv(
  ICC_results,
  file.path(group_output_dir, "ICC_results.csv")
)


# ------------------------------------------------------------
# Bland-Altman analysis
# ------------------------------------------------------------
# Preserve original DWI methodology:
# diff = v1 - v2
# ave = (v1 + v2) / 2
# reldiff = 100 * diff / ave
# Bias and limits of agreement are calculated on reldiff.

bland_altman_dir <- file.path(group_output_dir, "BlandAltman")
dir.create(bland_altman_dir, recursive = TRUE, showWarnings = FALSE)

calculate_bland_altman_summary <- function(pairs, analysis_label) {
  
  pairs %>%
    na.omit() %>%
    group_by(parameter) %>%
    summarise(
      N_pairs = n(),
      Bias = mean(reldiff),
      SD_difference = sd(reldiff),
      Lower_LoA = Bias - 1.96 * SD_difference,
      Upper_LoA = Bias + 1.96 * SD_difference,
      .groups = "drop"
    ) %>%
    filter(N_pairs >= 3) %>%
    mutate(
      Analysis = analysis_label,
      .before = parameter
    ) %>%
    rename(Parameter = parameter)
  
}

create_bland_altman_plot <- function(
    pairs,
    summary_row,
    analysis_label,
    parameter_name,
    group_label
) {
  
  plot_data <- pairs %>%
    filter(parameter == parameter_name) %>%
    na.omit() %>%
    mutate(
      site = factor(
        sprintf("%02d", as.integer(site)),
        levels = c("01", "02", "03", "04")
      )
    )
  
  x_label <- switch(
    parameter_name,
    "T1"    = "Mean T1 (ms)",
    "MOLLI" = "Mean MOLLI T1 (ms)",
    "T2"    = "Mean T2 (ms)",
    "Mean of paired measurements"
  )
  
  n_sites <- length(levels(plot_data$site))
  
  colours <- c(
    "#0057e7",
    "#d62d20",
    "#2ca02c",
    "#800080"
  )[seq_len(n_sites)]
  
  shapes <- c(
    16, # circle
    17, # triangle
    15, # square
    18  # diamond
  )[seq_len(n_sites)]
  
  ggplot(
    plot_data,
    aes(
      x = ave,
      y = reldiff
    )
  ) +
    
    geom_point(
      aes(
        colour = site,
        shape = site
      ),
      size = 3.1,
      alpha = 0.9
    ) +
    
    scale_colour_manual(values = colours) +
    
    scale_shape_manual(values = shapes) +
    
    geom_hline(
      data = summary_row,
      aes(
        yintercept = Bias,
        linetype = "Mean value"
      ),
      linewidth = 0.6
    ) +
    
    geom_hline(
      data = summary_row,
      aes(
        yintercept = Lower_LoA,
        linetype = "Limits of agreement"
      ),
      linewidth = 0.5
    ) +
    
    geom_hline(
      data = summary_row,
      aes(
        yintercept = Upper_LoA,
        linetype = "Limits of agreement"
      ),
      linewidth = 0.5
    ) +
    
    scale_linetype_manual(
      values = c(
        "Mean value" = "solid",
        "Limits of agreement" = "dashed"
      )
    ) +
    
    labs(
      title = paste(
        parameter_name,
        analysis_label,
        "-",
        group_label
      ),
      x = x_label,
      y = "Relative difference (%)",
      colour = "Center",
      shape = "Center",
      linetype = ""
    ) +
    
    theme_bw() +
    
    theme(
      plot.title = element_text(
        hjust = 0.5,
        size = rel(1.5)
      ),
      
      axis.title = element_text(
        size = rel(1.5)
      ),
      
      axis.text = element_text(
        size = rel(1.2)
      ),
      
      legend.title = element_text(
        size = rel(1.3)
      ),
      
      legend.text = element_text(
        size = rel(1.2)
      )
    )
  
}

run_bland_altman <- function(
    dataset,
    visit1,
    visit2,
    analysis_label,
    group_label
) {
  
  pairs <- make_visit_pairs(
    dataset,
    visit1,
    visit2
  ) %>%
    mutate(
      reldiff = 100 * diff / ave
    )
  
  summary <- calculate_bland_altman_summary(
    pairs,
    analysis_label
  )
  
  for (parameter_name in summary$Parameter) {
    
    summary_row <- summary %>%
      filter(
        Parameter == parameter_name
      )
    
    plot <- create_bland_altman_plot(
      pairs = pairs,
      summary_row = summary_row,
      analysis_label = analysis_label,
      parameter_name = parameter_name,
      group_label = group_label
    )
    
    output_file <- file.path(
      bland_altman_dir,
      paste0(
        analysis_label,
        "_",
        parameter_name,
        "_BlandAltman.pdf"
      )
    )
    
    ggsave(
      filename = output_file,
      plot = plot,
      device = "pdf",
      width = 7.5,
      height = 5.5,
      units = "in"
    )
    
  }
  
  summary
  
}

BlandAltman_summary <- purrr::imap_dfr(
  
  analyses,
  
  ~ run_bland_altman(
    dataset = .x$data,
    visit1 = .x$visit1,
    visit2 = .x$visit2,
    analysis_label = str_to_title(.y),
    group_label = group_label
  )
  
)

write_csv(
  BlandAltman_summary,
  file.path(
    bland_altman_dir,
    "BlandAltman_summary.csv"
  )
)

cat("\n==============================\n")
cat("Bland-Altman summary\n")
cat("==============================\n")
print(BlandAltman_summary)

cat("\nAll outputs saved in:", group_output_dir, "\n")
}

run_group_analysis(
  group_name = "HealthyVolunteers",
  group_label = "Healthy Volunteers",
  repeatability_file = file.path(
    analysis_dir,
    "Repeatability_HealthyVolunteers_input.csv"
  ),
  reproducibility_file = file.path(
    analysis_dir,
    "Reproducibility_HealthyVolunteers_input.csv"
  )
)

run_group_analysis(
  group_name = "CKDPatients",
  group_label = "CKD Patients",
  repeatability_file = file.path(
    analysis_dir,
    "Repeatability_Patients_input.csv"
  ),
  reproducibility_file = file.path(
    analysis_dir,
    "Reproducibility_Patients_input.csv"
  )
)
